### ISSUE TITLE
MacVim

### ISSUE THREAD

**Issue by amunra81** [eagletmt/neco-ghc#12]
I'm using the same configuration of vim on windows and mac (i have my .vim folder on a git repository https://github.com/amunra81/vim.git ). The neco-ghc on windows it works very well, but on os x it shows (on the completion popup list) just elements from the file(s) i have it opened and no functions from imported library or others.

1st fact) when I have the neocompletion off the Omnicomplition (C-X,C-U) it shows me the full list of completion elements. But when I put NeoComplCacheEnable , only elements from the page appears

2nd fact) ghc-mod works fine in command line, in VimShell and also with VimProc

**Comment by Shougo** [comment]
Too old issue.
