### ISSUE TITLE
No autocomplete for YouCompleteMe

### ISSUE THREAD

**Issue by euclio** [eagletmt/neco-ghc#28]
I've done the following to attempt to alleviate the problem:
- ghc-mod installed from the [haskell-core] repo on Arch Linux, version 3.1.5
- Ensured that ghc-mod is on my PATH
- Up-to-date versions of both YouCompleteMe and neco-ghc
- added `setlocal omnifunc=necoghc#omnifunc` to my `.vimrc`

However, I don't get any autocompletions at all, beyond simple textual suggestions. I'm not sure if installing ghc-mod from cabal would solve the problem, but I'd rather not do this if I don't have to.

**Comment by ches** [comment]
Does this behavior (triggering only on `.`) preclude the "importing a function of a module" feature of neco-ghc from working with YouCompleteMe?

I want to love neocomplete, I tried a lot of configuration tweaking to optimize sources, etc., but it's just too slow for me :disappointed:

**Comment by ches** [comment]
Apologies, importing functions from a module is working correctly, one just again needs to invoke `Ctrl-Space` manually to get the completions to appear. I had an incorrect config setting and wasn't seeing this working at first, all good now.

**Comment by CookiesBestDinner** [comment]
`.` doesn't seem like a suitable trigger for Haskell

What about:

```
let g:ycm_semantic_triggers = {'haskell' : ['re!.*']}
```

(I wouldn't know if that's doing something evil)

**Comment by siurius** [comment]
@CookiesBestDinner Works perfect! Thank you!
