### ISSUE TITLE
Only prelude functions are available for completion

### ISSUE THREAD

**Issue by jeremyjh** [eagletmt/neco-ghc#35]
I used to have this working, but I've switched from using hsenv to using cabal sandboxes and function completion no longer works correctly. No matter what has been imported, only Prelude functions are available for completion; basically my import statements are ignored. 

Setting let g:necoghc_debug = 1 in my .vimrc produces no additional output.

The other completions, such as import completions, work just fine. Any ideas?

**Comment by dkasak** [comment]
Just discovered this myself. To reiterate, LANGUAGE pragmas completely break completion other than for Prelude identifiers. Also, completion of pragmas and LANGUAGE extensions is broken (it lists Prelude identifiers instead of possible pragmas/extensions).

**Comment by dkasak** [comment]
@jeremyjh Any chance you got bitten by an issue similar to mine in #43?

**Comment by Shougo** [comment]
OK.  It seems problem.  I will check the code.

**Comment by Shougo** [comment]
@jeremyjh I think your syntax is broken.  So neco-ghc ignores it.
Please upload your Haskell syntax screenshot.

**Comment by jeremyjh** [comment]
Are you trying a file with a language pragma?  GHC is fine with my syntax.

**Comment by Shougo** [comment]
I will test it.   Please upload minimal .vimrc and the reproduce ways.

**Comment by Shougo** [comment]
No response.
