### ISSUE TITLE
Can't make completion to work with neocomplete

### ISSUE THREAD

**Issue by pablox-cl** [eagletmt/neco-ghc#41]
I just don't know what it's going on. It seems that neocomplete is not sourcing necoghc... because if I force omnicompletion (`<C-x><C-o>`) it works fine. 

```
:NecoGhcDiagnostics
Current filetype: haskell
ghc-mod is executable: 1
omnifunc: necoghc#omnifunc
neocomplete.vim: 2
neocomplcache.vim: 0
YouCompleteMe: 0
vimproc.vim: 800
ghc-mod:
Imported modules: Prelude
Number of symbols in Prelude: 235
```

For example, `|` is the cursor:

```
{-# LANGUAGE im|
```

... only shows neosnippet completions.

My neocomplete configuration is quite simple:

```
let g:neocomplete#enable_at_startup=1
```

How can I continue troubleshooting this?

**Comment by jarandaf** [comment]
I experience the same issue as @PaBLoX-CL (`:call necoghc#ghc_mod_version()` not returning anything but omni-completion works). My `ghc-mod` version is `5.2.1.2 compiled by GHC 7.8.4`. To be noticed, I installed this and other vim plugins via nix package manager, although I don't think this is important.

**Comment by Shougo** [comment]
Please upload your `ghc-mode version` output.

**Comment by jarandaf** [comment]
`ghc-mod version 5.2.1.2 compiled by GHC 7.8.4`

**Comment by Shougo** [comment]
I tested your version number, but the version is detected.
I think your neco-ghc is not latest version.

**Comment by jarandaf** [comment]
That is possible, nix usually doesn't offer latest versions but stable and compatible ones (in relation to other packages). I will investigate on that, thanks.
