### ISSUE TITLE
Add support for literate haskell

### ISSUE THREAD

**Issue by dbeecham** [eagletmt/neco-ghc#47]
I would like to see support for literate haskell in neco-ghc. 

(1) A very rough, but probably acceptable as a temporary solution, is to merely filter out any "> " on line beginnings (substitute(line, "^> ", "")) before parsing the line. 
(2) A better solution is to only treat lines beginning with "> " as haskell, and any other as text.
(3) In addition to bird-style ("> code"), there is also LaTeX-style literate haskell, though since this is not decidable per-line, some state-keeping is necessary, which makes implementation harder. I don't use this style of coding, and I personally don't see the benefit in using it, so I don't really care.

I'm trying to understand the code in order to implement (1) and hopefully (maybe) (2), but there is a slight lack of comments in the code (this is somewhat ironic, considering what I'm trying to do :)), so I wanted to create this issue to see if I could get any help in this. If not in coding, then perhaps some help in understanding all the bits and pieces.

**Comment by Shougo** [comment]
Thanks.  Any examples of literal haskell?

**Comment by dbeecham** [comment]
No, sorry, I haven't got any good examples at hand. I've really only just gotten started with a project in literate haskell. :)

**Comment by Shougo** [comment]
OK, thanks.

**Comment by dbeecham** [comment]
This issue is now a mix of fixed and dead; closing.

**Comment by Shougo** [comment]
OK.
