### ISSUE TITLE
necoghc#omnifunc used but no smart suggestions (YouCompleteMe)

### ISSUE THREAD

**Issue by elvis-sik** [eagletmt/neco-ghc#50]
Hi. I am using YouCompleteMe and neco-ghc (installed from Vundle) on vim 7.4.

I've done the

    let g:ycm_semantic_triggers = {'haskell' : ['.']}

and added what I was supposed to add to the ftype file.  `:echo &omnifunc` returns `necoghc#omnifunc` when I open a .hs file.

However, I only get the generic suggestions that YouCompleteMe gives. For example, I have a `LANGUAGE` pragma, so I get `LANGUAGE` as a suggestion if I type `LANG`. But if I try to do the fancy imports, for example, as shown in readme.md, I get nothing.

I tried hitting C-x, C-o, C-space and C-p.

**Comment by Shougo** [comment]
Please check if necoghc is works without YouCompleteMe.

**Comment by elvis-sik** [comment]
I installed neocomplete and it worked (and it seems nice). If you want to close the issue that's fine, otherwise we can investigate.

**Comment by Shougo** [comment]
OK.  I don't know YouCompleteMe omnifunc trigger behavior.
It may be YouCompleteMe problem.
