### ISSUE TITLE
Completion not working for pragma and language

### ISSUE THREAD

**Issue by albertnetymk** [eagletmt/neco-ghc#51]
Minimal vimrc to reproduce the problem.
```
if has('vim_starting')
  if &compatible
    set nocompatible
  endif

  runtime macros/matchit.vim
  set runtimepath+=~/.vim/bundle/neobundle.vim/
endif

call neobundle#begin(expand('~/.vim/bundle/'))
NeoBundleFetch 'Shougo/neobundle.vim'
NeoBundle 'eagletmt/neco-ghc'

call neobundle#end()
filetype plugin indent on
setlocal omnifunc=necoghc#omnifunc
```
```
vim -u ~/.vimrc hello.hs
```
Following the example in readme, type `{-# OP|`, `|` is where cursor is, then hit `<c-x><c-o>`, it says `Omni completion (^O^N^P) Pattern not found`.

The same for language completion case in the readme.

## ENV
vim: 7.4
nvim: ubuntu daily build

**Comment by Shougo** [comment]
https://github.com/eagletmt/neco-ghc/issues/43

Please upload your ghc-mod version.

**Comment by Shougo** [comment]
I tested it in ghc-mod from github and it works.

**Comment by albertnetymk** [comment]
My fault. `-u {vimrc}` option would skip all other initializations other than {vimrc}, which is why completion doesn't work for `vim -u ~/.vimrc hello.hs`.

Did bisect search on my `.vimrc`, and concluded that `hasksyn` is the culprit. After removing it, completion works as expected. Sorry for the noise.
