### ISSUE TITLE
Failed to autocomplete after using cabal, reporting permission denied

### ISSUE THREAD

**Issue by HuStmpHrrr** [eagletmt/neco-ghc#52]
Hi, 

if my project has cabal setup, autocompletion stops working. if I just write some haskell script wildly it works perfectly.

it reports:
> cabal-helper-wrapper: /home/hu/.ghc-mod/cabal-helper/cabal-helper-0.3.6.0-Cabal-1.22.2.0: createProcess: runInteractiveProcess: exec: permission denied (Permission denied)

and

> ghc-mod: readCreateProcess: /home/hu/.cabal/libexec/cabal-helper-wrapper "/home/hu/Projects/Haskell/TestProject/dist" "entrypoints" "source-dirs" "ghc-options" "ghc-src-options" "ghc-pkg-options" "ghc-merged-pkg-options" "ghc-lang-options" "--with-ghc=ghc" "--with-ghc-pkg=ghc-pkg" "--with-cabal=cabal" (exit 1): failed

however, `ghcmod` is install under my home folder, there shouldn't be permission issue. Could you help and have a look at that?

following is a brandnew test project just to try presence of cabal.

![errr](https://cloud.githubusercontent.com/assets/6101711/8945759/5e645064-3558-11e5-8e0d-bedcbfcf21ba.png)

**Comment by DanielG** [comment]
Well check the permissions of `/home/hu/.ghc-mod/cabal-helper/cabal-helper-0.3.6.0-Cabal-1.22.2.0` and see if it's really missing `+x`. If in doubt `rm -rf ~/.ghc-mod/cabal-helper` cleans that out and starts from scratch.

**Comment by HuStmpHrrr** [comment]
thanks. it was the reason.
