### ISSUE TITLE
Documentation could be improved

### ISSUE THREAD

**Issue by mpilman** [eagletmt/neco-ghc#53]
neco-ghc was not working for me, even though I followed the documentation. The documentation says that the following line should be added to .vim/ftplugin/haskell.vim:

    setlocal omnifunc=necoghc#omnifunc

First of all, this is imho a bad idea anyway (I am using git to keep my plugins up to date and I don't want to push them). Furthermore, it just did not work.

Fixing the first one is easier. IMHO it would be better, if the documentation would say, that one should add the following to the .vimrc:

    autocmd FileType haskell setlocal omnifunc=necoghc#omnifunc

The problem is, that haskell-vim overrides the omnifunc variable in compiler/ghc.vim - so if one has the haskell-vim installed, the following line is necessary as well (also in .vimrc):

    let g:haskellmode_completion_ghc=0

After this change, everything works like a charme

**Comment by Shougo** [comment]
Thanks.  Fixed.
