### ISSUE TITLE
Poor error behaviour when failing to find project root.

### ISSUE THREAD

**Issue by expipiplus1** [eagletmt/neco-ghc#60]
I encountered this issue when using a combination of nix and stack.

I have ghc-7.10.3 installed, but my stack.yaml specified using ghc-7.10.2.

During the call to `necoghc#boot` `s:get_ghcmod_root` returned this string:

```
Compiler version mismatched, found ghc-7.10.3 (x86_64), but expected minor version match with ghc-7.10.2 (x86_64) (based on resolver setting in /home/jophish/project/stack.yaml).
Try running "stack setup" to install the correct GHC into /home/jophish/.stack/programs/x86_64-linux/
Bootstrapping stack project
environment failed: readCreateProcess: /home/jophish/.nix-profile/bin/stack "path" (exit 1): failed
```

Although this error isn't the fault of neco-ghc the error message returned from the vimscript was fairly cryptic:

```
Error detected while processing function necoghc#boot..<SNR>104_ghc_mod_caching_browse..<SNR>104_ghc_mod:
line   13:
E77: Too many file names
Error detected while processing function necoghc#boot..<SNR>104_ghc_mod_caching_browse:
line   12:
E170: Missing :endfor
```

It would be nice for neco-ghc to bubble up this error message to the vim user.

**Comment by Shougo** [comment]
Yes, I think the error behavior should be improved too.

**Comment by expipiplus1** [comment]
An easier way to reproduce this is to move  `~/.stack/config.yaml` to `~/.stack/stack.yaml` to cause stack to issue a warning.

**Comment by expipiplus1** [comment]
It's perhaps worth noting also that being in the project root is no longer necessary since ghc-mod 5.5

**Comment by expipiplus1** [comment]
or an even easier way to reproduce this is to put an empty stack.yaml in the directory!

**Comment by Shougo** [comment]
> It's perhaps worth noting also that being in the project root is no longer necessary since ghc-mod 5.5

Please describe it.  Or please create the Pull Request.
If it is not needed, I will remove the code.

**Comment by expipiplus1** [comment]
@Shougo This is the change I was talking about in ghc-mod
https://github.com/DanielG/ghc-mod/issues/665

**Comment by Shougo** [comment]
Thank you.  Fixed.

**Comment by expipiplus1** [comment]
It's probably worth mentioning that this now only works with ghc-mod 5.5+

**Comment by Shougo** [comment]
i have added it.
