### ISSUE TITLE
unclear complete candidates order  

### ISSUE THREAD

**Issue by bravomikekilo** [eagletmt/neco-ghc#64]
It is very wired that the complete candidates are sorted in a mystery way 
![screenshot from 2016-05-21 21-18-31](https://cloud.githubusercontent.com/assets/17548436/15448631/f072d238-1f99-11e6-94a1-b9346fafa45e.png)
everything is right except the order
maybe is my misconfig
this is my init.vim(vimrc)
[init (copy).txt](https://github.com/eagletmt/neco-ghc/files/275874/init.copy.txt)
in othercase  it always start with the longest one
I use the neco-ghc neovim and deoplete

**Comment by Shougo** [comment]
It is the deoplete feature.
It is sorted by `sorter_rank`.  You can disable it by `deoplete#custom#set()`.

**Comment by bravomikekilo** [comment]
thanks
I tried but I can't disable it 
call deoplete#custom#set('_','sorters',[])
or
call deoplete#custom#set('_','sorters','')
didn't work
so I tried the call deoplete#custom#set('buffer','rank',9999)
It solve part of problem but the import complete candidate is still misordered

**Comment by Shougo** [comment]
Your code is wrong.

```vim
call deoplete#custom#set('ghc','sorters',[])
```

**Comment by bravomikekilo** [comment]
`call deoplete#custom#set('ghc','sorters',[])`

sorry,

I correct the code but it still not work

**Comment by bravomikekilo** [comment]
[init (copy).txt](https://github.com/eagletmt/neco-ghc/files/276197/init.copy.txt)

**Comment by Shougo** [comment]
Reproduced.

**Comment by Shougo** [comment]
I have added sorter_word.

```vim
call deoplete#custom#set('ghc','sorters',['sorter_word'])
```

**Comment by bravomikekilo** [comment]
thanks ! my friend
