### ISSUE TITLE
Pass `--silent` flag to ghc-mod

### ISSUE THREAD

**Issue by jimenezrick** [eagletmt/neco-ghc#65]
When `ghc-mod` is invoked without the `--silent` flag it sometimes prints warning messages that mess with the Vim plugin parsing the output:

```
$ ghc-mod expand src/Model/Prob.hs 
Warning: 'dist/setup-config' exists, ignoring Stack and using cabal-install instead
Dummy:0:0:Error:src/Model/Types.hs:197:1-19: Splicing declarations
```
```
$ ghc-mod --silent expand src/Model/Prob.hs 
Dummy:0:0:Error:src/Model/Types.hs:197:1-19: Splicing declarations 
```

`ghc-mod` should be probably always invoked with `--silent` to get clean output.

**Comment by DanielG** [comment]
No actually neco-ghc should pass something like `--line-prefix=o,e` so it can seperate stdout and stderr output by looking at the first character of each line output by ghc-mod and then log stuff on the stderr stream for later display (say when an error occurs). See also the discussion in https://github.com/DanielG/ghc-mod/issues/454 .

**Comment by Shougo** [comment]
OK, it should be fixed.

**Comment by jimenezrick** [comment]
I don't see new commits in this repository, let me know when the fix is published so I can test it :)

**Comment by Shougo** [comment]
Implemented.
