### ISSUE TITLE
How can I set a background image ?

### ISSUE THREAD

**Issue by skywind3000** [eagletmt/neco-ghc#68]
Just like that, how can you do that ?

![](https://camo.githubusercontent.com/101a8e27bbe73e372a120b7d73368741cc364b45/687474703a2f2f63616368652e6779617a6f2e636f6d2f66336432633039373437353032313631353538313832326565653863623666642e706e67)

**Comment by Shougo** [comment]
It is the occupacy.
I think it is terminal feature.
This is not plugin issue!

**Comment by skywind3000** [comment]
Thanks for answer such a question.
All the text in the terminal window should be transparent too, if it is a feature of the terminal.
But as I noticed, the line number columns and the status line are not transparent.

very strange

**Comment by Shougo** [comment]
Some Window manager has occupancy feature.
So it can available in GVim.
