### ISSUE TITLE
Accessing the full completion [Feature Request]

### ISSUE THREAD

**Issue by toonn** [eagletmt/neco-ghc#71]
I'm using neco-ghc with neocomplete.
When I type "import dtsu" the following completions show:
Data.~ [ghc] [ghc] Data.Sequence
Distribution.~ [ghc] [ghc] Distribution.TestSuite

These complete to "Data" and "Distribution" respectively. Is there a way to have them complete to Data.Sequence and Distribution.TestSuite?

Also, why does [ghc] show up twice?

**Comment by Shougo** [comment]
> These complete to "Data" and "Distribution" respectively. Is there a way to have them complete to Data.Sequence and Distribution.TestSuite?

It is converter_delimiter feature in neocomplete.  You can disable it.
Please read neocomplete documentation.

> Also, why does [ghc] show up twice?

I will fix it.
