### ISSUE TITLE
Empty error/warning: neco-ghc:            (use -v for more information)

### ISSUE THREAD

**Issue by wizzup** [eagletmt/neco-ghc#76]
I have got this warning message at the bottom of screen

![2017-08-02-182138_790x82_scrot](https://user-images.githubusercontent.com/342500/28871593-7c03805e-77af-11e7-91f2-39beb6952b10.png)

This is output from `:NecoGhcDiagnostics`

    Current filetype: haskell                                                                                                                                                                              
    ghc-mod is executable: 1                                                                                                                                                                               
    omnifunc: necoghc#omnifunc                                                                                                                                                                             
    neocomplete.vim: 0                                                                                                                                                                                     
    neocomplcache.vim: 0                                                                                                                                                                                   
    YouCompleteMe: 0                                                                                                                                                                                       
    vimproc.vim: 903                                                                                                                                                                                       
    ghc-mod: 5.7.0.0                                                                                                                                                                                       
    Imported modules: System.FilePath, Prelude, Text.Pandoc.Options, Data.Monoid, Hakyll, Data.List                                                                                                        
    Number of symbols in Prelude: 0                                                                                                                                                                        
    Press ENTER or type command to continue

I am using `NixOS`, `NeoVim` and `Shougo/deoplete.nvim`

**Comment by wizzup** [comment]
I did not aware of `:messages` command.

Would be nice if it also mentioned in [guideline](https://github.com/eagletmt/neco-ghc/blob/master/CONTRIBUTING.md)

    neco-ghc: EXCEPTION: browse:                                                                                                                                                                           
    neco-ghc:            <command line>: cannot satisfy -package-id hakyll-4.9.7.0-QwF9CFRvSI2XjU031axMw                                                                                                   
    neco-ghc:                (use -v for more information)                                                                                                                                                 
    neco-ghc: EXCEPTION: browse:                                                                                                                                                                           
    neco-ghc:            <command line>: cannot satisfy -package-id hakyll-4.9.7.0-QwF9CFRvSI2XjU031axMw                                                                                                   
    neco-ghc:                (use -v for more information)                                                                                                                                                 
    neco-ghc: EXCEPTION: browse:                                                                                                                                                                           
    neco-ghc:            <command line>: cannot satisfy -package-id hakyll-4.9.7.0-QwF9CFRvSI2XjU031axMw                                                                                                   
    neco-ghc:                (use -v for more information)                                                                                                                                                 
    neco-ghc: EXCEPTION: browse:                                                                                                                                                                           
    neco-ghc:            <command line>: cannot satisfy -package-id hakyll-4.9.7.0-QwF9CFRvSI2XjU031axMw                                                                                                   
    neco-ghc:                (use -v for more information)                                                                                                                                                 
    Press ENTER or type command to continue

**Comment by wizzup** [comment]
Seem like this is NixOS [issue](https://github.com/NixOS/nixpkgs/issues/27893), I should close this issue.

**Comment by Shougo** [comment]
OK.
