### ISSUE TITLE
My deoplete, neco-ghc auto complete displays duplicate ghc options...

### ISSUE THREAD

**Issue by EdmundsEcho** [eagletmt/neco-ghc#81]
This tool is a fantastic addition to the vim/nvim Haskell community.  Thank you!

Question/issue: How might I go about troubleshooting the duplicate entries in the selection list?  It only _duplicates_ the `ghc` entries (e.g, not local buffer, nor files).  I am using `stack`.  What does `neco-ghc` source to inform the choices?  Thank you in advance for helping me here.  - E

**Comment by Shougo** [comment]
I don't understand your issue.
Please upload the screenshot.

I think it is ghc-mod feature.
deoplete source does not remove duplicate candidates.

**Comment by EdmundsEcho** [comment]
I agree the issue could be that `ghc-mod` might be scanning both my project directories (e.g., `src app and test`) _and_ the compiled assembly of the code in the `.stack-work/` project directory.  

Another idea, for my `ALE` configuration I make sure to only use `stack-ghc-mode` (and not `ghc-mod`).  Might specifying a similar configuration for `neco-ghc` avoid duplicate entries?

 ![screen shot 2018-03-26 at 9 31 30 am](https://user-images.githubusercontent.com/11245417/37909312-89052ef0-30d8-11e8-862c-e0f2b68ea5f1.png)

**Comment by Shougo** [comment]
@EdmundsEcho Please test the patch.

https://github.com/Shougo/deoplete.nvim/issues/705#issue-308801138

**Comment by EdmundsEcho** [comment]
Hi Shougo,  While working on `echodoc`, I found an opportunity to help with the `neco-ghc` plugin.  I updated the `diagnostics.vim` and `necoghc.vim` files ever so slightly to augment the reporting capacity for a user using `stack`.   I will take down the repository once you had a chance to take a look to see if the work is helpful.  https://github.com/EdmundsEcho/neco-ghc-stack

**Comment by Shougo** [comment]
@EdmundsEcho I have read your changes.
Please create the PR for it.

**Comment by Shougo** [comment]
@EdmundsEcho https://github.com/Shougo/deoplete.nvim/issues/705#issuecomment-376733907

**Comment by Shougo** [comment]
I have fixed the problem and I cannot reproduce it.

**Comment by EdmundsEcho** [comment]
Got it.  FYI, I created the PR for the updates I sent you.

**Comment by Shougo** [comment]
OK
