### ISSUE TITLE
Autocomplete only shows local results w/ Deoplete

### ISSUE THREAD

**Issue by samuelbodin** [eagletmt/neco-ghc#85]
Hi, I'm struggling a bit to get neco-ghc working with deoplete. 

The problem: 
This error pops up as soon as I type "import"
![1](https://user-images.githubusercontent.com/19345463/62466456-a5b8bf80-b791-11e9-9eaa-3bc7b81f51d0.png)

And the only autocomplete suggestions I get are modules which I have already imported.
![2](https://user-images.githubusercontent.com/19345463/62466521-c5e87e80-b791-11e9-83bb-7b6aa9903e06.png)

NecoGhcDiagnostics:
![5](https://user-images.githubusercontent.com/19345463/62466663-22e43480-b792-11e9-99dc-0cbb980791b3.png)

I'm using Neovim, both packages installed via Plug,
![3](https://user-images.githubusercontent.com/19345463/62466244-3216b280-b791-11e9-8f3b-3010ce00e682.png)

with the following settings
![4](https://user-images.githubusercontent.com/19345463/62466382-799d3e80-b791-11e9-9a36-d53d6c1f7065.png)

Any idea of what I am missing?

**Comment by Shougo** [comment]
It seems ghc-mod's error instead of neco-ghc.
I cannot fix the issue.

**Comment by samuelbodin** [comment]
Additionally, I found this in vim message buffer. 

![1](https://user-images.githubusercontent.com/19345463/62502641-cc5a1300-b7f0-11e9-92dc-affdec6a5f8d.png)

**Comment by Shougo** [comment]
Yes.  It just prints ghc-mod error.
It is not neco-ghc error.

**Comment by samuelbodin** [comment]
Alright. I'm gonna be looking into Haskell IDE Engine, hopefully that works better :P
