### ISSUE TITLE
ghc-mod deprecation and state of this project

### ISSUE THREAD

**Issue by tchoutri** [eagletmt/neco-ghc#87]
Hi! Last year, [ghc-mod](https://github.com/DanielG/ghc-mod) was deprecated in favour of using [ghcide](https://github.com/digital-asset/ghcide).
Can we hope for some support for a Haskell deoplete source that would leverage LSP?

Thanks for the work!

**Comment by Shougo** [comment]
ghc-mod is replaced to hhp now.
https://github.com/eagletmt/neco-ghc/pull/86

For Haskell lsp, you should use other plugins.

So this question is closed.
