### ISSUE TITLE
Autocomplete only shows local/import results w/Deoplete

### ISSUE THREAD

**Issue by Luc-Saccoccio** [eagletmt/neco-ghc#88]
Using `hhp` (because `ghc-mod` is deprecated), only 1)pragma, 2)language and 3)imports are working. Neither 3)import of a function nor 4)functions based on importing modules are working properly, it's just showing local results.
I don't really want to change of completion engine (deoplete is exactly what I need), so is there a workaround ?
I'm still learning Haskell, and I don't know Vimscript, but if I can help, tell me how ^^
Here is the output of `NecoGhcDiagnostics` :
```
Current filetype: haskell
ghc-mod is executable: 0
hhpc-mod is executable: 1
omnifunc: necoghc#omnifunc
neocomplete.vim: 0
neocomplcache.vim: 0
YouCompleteMe: 0
vimproc.vim: not installed
ghc-mod: 0.0.3
Imported modules: Prelude
Number of symbols in Prelude: 0
```

**Comment by Shougo** [comment]
I think you can use LSP engine with deoplete.
https://github.com/lighttiger2505/deoplete-vim-lsp

> Using hhp (because ghc-mod is deprecated), only 1)pragma, 2)language and 3)imports are working. Neither 3)import of a function nor 4)functions based on importing modules are working properly, it's just showing local results.

`hhp` supports the feature?
neco-ghc is open source and you can check the output.

**Comment by Shougo** [comment]
And please upload the example code.
We have not ESP skills.

**Comment by Luc-Saccoccio** [comment]
> And please upload the example code.
> We have not ESP skills.

I'm sorry ! The problem occurs for every Haskell code I open (filetype is set to Haskell). An exemple could be this piece of code I wrote while read Learn You A Haskell :

![image](https://user-images.githubusercontent.com/70776630/108717506-a2c12380-751d-11eb-8322-fc408f6e7426.png)


The comand I wanted was `appendFile`.

> I think you can use LSP engine with deoplete.

I should be using [this](https://github.com/haskell/haskell-language-server) ? It seems quite big, and if possible, I'd rather use neco-ghc.

**Comment by Shougo** [comment]
I have tested and `hhpc browse -o System.IO` does not work.
The output is empty.

**Comment by Shougo** [comment]
> I should be using this ? It seems quite big, and if possible, I'd rather use neco-ghc.

Yes.  You should use it instead.

**Comment by Shougo** [comment]
Sorry.  I cannot help you.  Because `hhpc browse` does not work.
I have not magic.

**Comment by Shougo** [comment]
I know hls is big. But it should work.

**Comment by Shougo** [comment]
`hhp` does not support stack installation.
This is feature.

**Comment by Luc-Saccoccio** [comment]
>  This is feature.

[For reference](https://github.com/kazu-yamamoto/hhp/issues/11)

I'm going to test with Cabal, thanks for asking ^^
